# .goreleaser.yml
version: 2
release:
  disable: false
  # 覆盖之前的release
  replace_existing_draft: true
  prerelease: auto
  mode: replace
  # 允许快照版本发布
  allow_snapshot: true
  name_template: "Build {{.Tag}}"
before:
  hooks:
    # 删除已有的frontend文件夹
    - rm -rf frontend || true
    # 复制build到frontend
    - cp -r build frontend || true
    # 打包前先执行一些必要的操作
    - go mod tidy
    
# 源代码配置
source:
  enabled: true
  prefix_template: '{{ .ProjectName }}-source'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: "frontend/**/*"
        dst: "frontend"
      - src: "script/allinssl.sh"
        dst: "allinssl.sh"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goarch: ppc64
