services:
  allinssl:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: allinssl:local
    container_name: allinssl
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8888}:8888"
    volumes:
      # 持久化数据目录
      - ./data:/www/allinssl/data
      # 持久化日志目录
      - ./logs:/www/allinssl/logs
    environment:
      # 默认用户名
      - ALLINSSL_USER=${ALLINSSL_USER:-allinssl}
      # 默认访问地址
      - ALLINSSL_URL=${ALLINSSL_URL:-allinssl}
      # 默认密码（建议修改）
      - ALLINSSL_PWD=${ALLINSSL_PWD:-allinssldocker}
      - GIN_MODE=${GIN_MODE:-release}
      # 时区设置
      - TZ=${TZ:-Asia/Shanghai}
    networks:
      - allinssl-network

networks:
  allinssl-network:
    driver: bridge
