/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./../src/components/flowChart/components/other/addNode/index.tsx')['default']
    Alias: typeof import('./../src/components/flowChart/lib/alias.tsx')['default']
    ApplyNode: typeof import('./../src/components/flowChart/components/task/applyNode/index.tsx')['default']
    ApplyNodeConfig: typeof import('../../vueFlow/components/configs/ApplyNodeConfig.jsx')['default']
    BaseComponent: typeof import('./../src/components/baseComponent/index.tsx')['default']
    BaseNode: typeof import('./../src/components/flowChart/components/base/baseNode/index.tsx')['default']
    BaseNodeWithAddButton: typeof import('../../vueFlow/components/nodes/BaseNodeWithAddButton.jsx')['default']
    BranchNode: typeof import('./../src/components/flowChart/components/base/branchNode/index.tsx')['default']
    ConditionNode: typeof import('./../src/components/flowChart/components/base/conditionNode/index.tsx')['default']
    Config: typeof import('./../src/components/flowChart/lib/config.tsx')['default']
    CustomDrawer: typeof import('./../src/components/customDrawer/index.tsx')['default']
    DeployNode: typeof import('./../src/components/flowChart/components/task/deployNode/index.tsx')['default']
    DeployNodeConfig: typeof import('../../vueFlow/components/configs/DeployNodeConfig.jsx')['default']
    DnsProviderSelect: typeof import('./../src/components/dnsProviderSelect/index.tsx')['default']
    Drawer: typeof import('./../src/components/flowChart/components/other/drawer.tsx')['default']
    EmptyActionPrompt: typeof import('../src/components/emptyState/index.jsx')['default']
    EmptyState: typeof import('./../src/components/emptyState/index.tsx')['default']
    EndNode: typeof import('./../src/components/flowChart/components/base/endNode.tsx')['default']
    EndNodeConfig: typeof import('../../vueFlow/components/configs/EndNodeConfig.jsx')['default']
    ErrorNode: typeof import('./../src/components/flowChart/components/base/errorNode/index.tsx')['default']
    FlowChart: typeof import('./../src/components/flowChart/index.tsx')['default']
    LogViewer: typeof import('./../src/components/logViewer/index.tsx')['default']
    NewApplyNode: typeof import('../../vueFlow/components/nodes/NewApplyNode.jsx')['default']
    NewBranchNode: typeof import('../../vueFlow/components/nodes/NewBranchNode.jsx')['default']
    NewDeployNode: typeof import('../../vueFlow/components/nodes/NewDeployNode.jsx')['default']
    NewNotifyNode: typeof import('../../vueFlow/components/nodes/NewNotifyNode.jsx')['default']
    NewStartNode: typeof import('../../vueFlow/components/nodes/NewStartNode.jsx')['default']
    NewUploadNode: typeof import('../../vueFlow/components/nodes/NewUploadNode.jsx')['default']
    NodeWrap: typeof import('./../src/components/flowChart/components/render/nodeWrap.tsx')['default']
    NormalNode: typeof import('../../vueFlow/components/nodes/NormalNode.jsx')['default']
    NormalNodeConfig: typeof import('../../vueFlow/components/configs/NormalNodeConfig.jsx')['default']
    NotifyNode: typeof import('./../src/components/flowChart/components/task/notifyNode/index.tsx')['default']
    NotifyNodeConfig: typeof import('../../vueFlow/components/configs/NotifyNodeConfig.jsx')['default']
    NotifyProviderSelect: typeof import('./../src/components/notifyProviderSelect/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartNode: typeof import('./../src/components/flowChart/components/task/startNode/index.tsx')['default']
    StartNodeConfig: typeof import('../../vueFlow/components/configs/StartNodeConfig.jsx')['default']
    SvgIcon: typeof import('./../src/components/svgIcon/index.tsx')['default']
    TypeIcon: typeof import('./../src/components/typeIcon/index.tsx')['default']
    UploadNode: typeof import('./../src/components/flowChart/components/task/uploadNode/index.tsx')['default']
    UploadNodeConfig: typeof import('../../vueFlow/components/configs/UploadNodeConfig.jsx')['default']
    UseController: typeof import('./../src/components/flowChart/useController.tsx')['default']
    UseStore: typeof import('./../src/components/flowChart/useStore.tsx')['default']
    Verify: typeof import('./../src/components/flowChart/components/task/applyNode/verify.tsx')['default']
    VueFlow: typeof import('../../vueFlow/index.jsx')['default']
    WorkflowEditor: typeof import('../../vueFlow/components/WorkflowEditor.jsx')['default']
    WorkflowNodeConfig: typeof import('../../vueFlow/components/WorkflowNodeConfig.jsx')['default']
  }
}
