/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./../src/components/FlowChart/components/other/addNode/index.tsx')['default']
    Alias: typeof import('./../src/components/FlowChart/lib/alias.tsx')['default']
    BaseLayout: typeof import('./../src/components/BaseLayout/index.tsx')['default']
    BaseNode: typeof import('./../src/components/FlowChart/components/base/baseNode/index.tsx')['default']
    BranchNode: typeof import('./../src/components/FlowChart/components/base/branchNode/index.tsx')['default']
    CAProviderSelect: typeof import('./../src/components/CAProviderSelect/index.tsx')['default']
    ConditionNode: typeof import('./../src/components/FlowChart/components/base/conditionNode/index.tsx')['default']
    Config: typeof import('./../src/components/FlowChart/lib/config.tsx')['default']
    DnsProviderSelect: typeof import('./../src/components/DnsProviderSelect/index.tsx')['default']
    Drawer: typeof import('./../src/components/FlowChart/components/other/drawer.tsx')['default']
    EndNode: typeof import('./../src/components/FlowChart/components/base/endNode.tsx')['default']
    ErrorNode: typeof import('./../src/components/FlowChart/components/base/errorNode/index.tsx')['default']
    FlowChart: typeof import('./../src/components/FlowChart/index.tsx')['default']
    LogDisplay: typeof import('./../src/components/LogDisplay/index.tsx')['default']
    NodeWrap: typeof import('./../src/components/FlowChart/components/render/nodeWrap.tsx')['default']
    NotifyProviderSelect: typeof import('./../src/components/NotifyProviderSelect/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.tsx')['default']
    TableEmptyState: typeof import('./../src/components/TableEmptyState/index.tsx')['default']
    TypeIcon: typeof import('./../src/components/TypeIcon/index.tsx')['default']
    UpdateLogModal: typeof import('./../src/components/UpdateLogModal/index.tsx')['default']
    UseController: typeof import('./../src/components/CAProviderSelect/useController.tsx')['default']
    UseStore: typeof import('./../src/components/FlowChart/useStore.tsx')['default']
    Verify: typeof import('./../src/components/FlowChart/lib/verify.tsx')['default']
  }
}
