/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface DomainQueryCheckResponseData {
  /** 数据 */
  data: Datum[]
  /** 页码 */
  page: string
  /** 每页数量 */
  row: string
  /** 时间 */
  shift: string
}

export interface Datum {
  /** 可注册 */
  available: boolean
  /** 域名 */
  domain: string
  /** 价格信息 */
  price_info: PriceInfo
  /** 查询时间 */
  query_time: Date
  /** 状态 */
  status: Status
  /** 状态描述 */
  status_desc: StatusDesc
  /** 后缀 */
  suffix: string
}

export interface PriceInfo {
  /** 成本价格 */
  cost_price: number
  /** 描述 */
  description: null | string
  /** 域名类型 */
  domain_type: number
  /** 第一年折扣价格 */
  first_year_discount_price: number
  /** 第一年价格 */
  first_year_price: number
  /** 最大注册年限 */
  max_register_years: number
  /** 最低价格限制 */
  min_price_limit: number
  /** 最少注册年限 */
  min_register_years: number
  /** 推荐类型 */
  recommend_type: number
  /** 赎回折扣价格 */
  redemption_discount_price: number
  /** 赎回价格 */
  redemption_price: number
  /** 续费价格 */
  renew_price: number
  /** 续费折扣价格 */
  renewal_discount_price: number
  /** 排序顺序 */
  sort_order: number
  /** 状态 */
  status: number
  /** 后缀 */
  suffix: string
  /** 转移折扣价格 */
  transfer_discount_price: number
  /** 转移价格 */
  transfer_price: number
}

/** 状态：registered 表示已注册，available 表示可注册 */
export type Status = 'registered' | 'available'

/** 状态中文描述 */
export type StatusDesc = '已注册' | '可注册'

export interface DomainQueryCheckRequest {
  /** 要查询的域名，不含后缀的主机名部分 */
  domain: string
  /** 页码（可选），用于分页查询，从1开始 */
  p?: number
  /** 每页行数（可选），指定查询结果的数量 */
  rows?: number
  /** 回调函数名（可选），用于JSONP请求 */
  callback?: string
  /** 推荐类型（可选），用于筛选特定类型的推荐域名后缀 */
  recommend_type?: number
}
