/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderDetailResponseData {
  /** 取消原因，未取消时为 null */
  cancel_reason: string | null
  /** 取消时间（Unix 时间戳，秒），未取消时为 null */
  cancel_time: number | null
  /** 完成时间（Unix 时间戳，秒），未完成时可能为 0 */
  complete_time: number
  /** 创建时间（Unix 时间戳，秒） */
  created_at: number
  /** 过期时间（Unix 时间戳，秒） */
  expire_time: number
  /** 订单ID */
  id: number
  /** 订单项列表 */
  items: OrderItem[]
  /** 订单号 */
  order_no: string
  /** 订单类型 */
  order_type: number
  /** 原始价格（字符串表示，单位元） */
  original_price: string
  /** 产品类型（例如：domain） */
  product_type: string
  /** 退款原因，未退款时为 null */
  refund_reason: string | null
  /** 退款时间（Unix 时间戳，秒），未退款时为 null */
  refund_time: number | null
  /** 订单来源（例如：website） */
  source: string
  /** 订单状态 */
  status: number
  /** 订单总金额（字符串表示，单位元） */
  total_amount: string
  /** 用户ID */
  uid: number
  /** 更新时间（Unix 时间戳，秒） */
  updated_at: number
}

/** 订单项 */
export interface OrderItem {
  /** 创建时间（Unix 时间戳，秒） */
  created_at: number
  /** 折扣后单价（字符串表示，单位元） */
  discount_price: string
  /** 域名ID */
  domain_id: number
  /** 域名（不含后缀） */
  domain_name: string
  /** 附加服务类型 */
  domain_service: number
  /** 附加服务价格（单位元） */
  domain_service_price: number
  /** 域名类型 */
  domain_type: number | null
  /** 错误信息 */
  error_message: string
  /** 完整域名（含后缀） */
  full_domain: string
  /** 订单项ID */
  id: number
  /** 单价（字符串表示，单位元） */
  one_price: string
  /** 所属订单ID */
  order_id: number
  /** 订单类型 */
  order_type: number
  /** 处理时间（Unix 时间戳，秒），未处理时为 null */
  process_time: number | null
  /** 实名模板ID */
  real_name_template_id: number
  /** 退款金额（字符串表示，单位元） */
  refund_amount: string
  /** 子订单号 */
  son_order_no: string
  /** 订单项状态 */
  status: number
  /** 后缀 */
  suffix: string
  /** 订单项总金额（字符串表示，单位元） */
  total_amount: string
  /** 用户ID */
  uid: number
  /** 更新时间（Unix 时间戳，秒） */
  updated_at: number
  /** 注册年限（年） */
  years: number
}

export interface OrderDetailRequest {
  /** 订单号 */
  order_no: string
}
