/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCartUpdateResponseData {}

export interface OrderCartUpdateRequest {
  /** 购物车条目ID */
  cart_id: number
  /** 购买年限（单位：年） */
  years: number
  /** 是否选中（0未选中，1选中） */
  is_selected: number
}
