/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCartClearResponseData {
  /** 是否清空成功 */
  success: boolean
}

/**
 * 清空购物车请求参数
 * 无需额外参数
 */
export interface OrderCartClearRequest {}
