/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCartRemoveResponseData {
  /** 被移除的购物车条目ID */
  cart_id: number
  /** 是否移除成功 */
  success: boolean
}

export interface OrderCartRemoveRequest {
  /** 需要移除的购物车条目ID */
  cart_id: number
}
