/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface ContactGetUserDetailResponseData {
  /** 数据 */
  data: Datum[]
  /** 页码 */
  page: string
  /** 每页数量 */
  row: string
  /** 时间 */
  shift: string
}

export interface Datum {
  /** 地址（中文） */
  address: string
  /** 地址（英文） */
  address_en: string
  /** 营业执照 */
  business_license: string
  /** 城市 */
  city: string
  /** 联系人姓名 */
  contact_person: string
  /** 创建时间（Unix 时间戳，秒） */
  created_at: number
  /** 邮箱 */
  email: string
  /** 审核失败原因 */
  fail_reason: string
  /** 模板ID */
  id: number
  /** 证件照背面URL */
  id_image_back: string
  /** 证件照正面URL */
  id_image_front: string
  /** 证件号码 */
  id_number: string
  /** 证件类型 */
  id_type: number
  /** 是否默认模板：1默认，0非默认 */
  is_default: number
  /** 所有者名称（中文） */
  owner_name: string
  /** 所有者名称（英文） */
  owner_name_en: string
  /** 联系电话 */
  phone: string
  /** 邮政编码 */
  postal_code: string
  /** 注册者ID（注册局侧） */
  registrant_id: string
  /** 模板状态码 */
  status: number
  /** 模板名称 */
  template_name: string
  /** 模板状态描述 */
  template_status: string
  /** 模板类型（个人/企业等） */
  type: number
  /** 用户ID */
  uid: number
  /** 更新时间（Unix 时间戳，秒） */
  updated_at: number
  /** 审核通过时间（Unix 时间戳，秒） */
  verify_time: number
}

export interface ContactGetUserDetailRequest {
  /** 页码（可选），用于分页查询，从1开始 */
  p?: number
  /** 模板类型（可选） */
  type?: number
  /** 每页行数（可选），指定查询结果的数量 */
	rows?: number
	status?: number
}
