/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCartAddResponseData {}

export interface OrderCartAddRequest {
  /** 域名主机名（不含后缀），例如 "example" */
  domain_name: string
  /** 域名后缀，例如 ".com"、".net" */
  suffix: string
  /** 域名服务类型（可选），如注册/续费/转移等 */
  type?: number
  /** 购买年限（可选），单位：年 */
  years?: number
  /** 域名ID（可选），当针对已有域名操作时使用 */
  domain_id?: number
}
