/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderPaymentStatusResponseData {
  /** 订单状态，1:已支付，0:未支付 */
  status: 1 | 0
}

export interface OrderPaymentStatusRequest {
  /** 订单号 */
  order_no: string
}
