/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCreateResponseData {
  /** 支付宝支付链接 */
  ali: string
  /** 订单创建时间 */
  create_time: string
  /** 折扣金额 */
  discount_price: number
  /** 域名数量 */
  domain_count: number
  /** 订单过期时间 */
  expire_time: string
  /** 订单ID */
  order_id: number
  /** 订单编号 */
  order_no: string
  /** 原价 */
  original_price: number
  /** 支付链接 */
  payment_url: string
  /** 总价 */
  total_price: number
  /** 微信支付链接 */
  wx: string
}

export interface OrderCreateRequest {
  /** 实名模板ID，用于绑定订单的实名认证信息 */
  real_name_template_id: number
  /** 订单类型，例如 1: 注册，2: 续费，3: 转移 */
  order_type: number
  /** 购物车条目ID列表，用于生成订单 */
  cart_ids: number[]
}
