/* Auto-generated by quicktype from API response. Do not edit by hand. */
export interface OrderCartListResponseData {
  /** 购物车条目列表 */
  items: Item[]
  /** 原价合计（未优惠） */
  original_price: number
  /** 已选中条目的数量 */
  selected_count: number
  /** 已选中条目的价格合计 */
  selected_price: number
  /** 购物车总条目数量 */
  total_count: number
  /** 购物车总价（可能包含优惠后价格） */
  total_price: number
}

export interface Item {
  /** 订单创建时间 */
  created_at: number
  /** 域名名称 */
  domain_name: string
  /** 域名服务 */
  domain_service: number
  /** 域名服务价格 */
  domain_service_price: number
  /** 订单过期时间 */
  expire_time: number
  /** 完整域名 */
  full_domain: string
  /** 订单ID */
  id: number
  /** 原价 */
  original_price: number
  /** 价格 */
  price: number
  /** 实名模板ID */
  real_name_template_id: null
  /** 选中状态 */
  selected: number
  /** 会话ID */
  session_id: string
  /** 来源 */
  source: null
  /** 后缀 */
  suffix: string
  /** 用户ID */
  uid: number
  /** 订单更新时间 */
  updated_at: number
  /** 域名年限 */
  years: number
}

export interface OrderCartListRequest {}
